### ISSUE TITLE
ma-extension-error on export

### ISSUE THREAD

**Issue by christianbormann** [sorengranfeldt/psma#10]
When exporting attribute changes we get an error since a few days:

> Error: ma-extension-error
> Connected data source error code: 0x80230703
> Connected data source error: unexpected-error
> 

In the Windows eventlog we get the following error:
```
The extensible extension returned an unsupported error.
 The stack trace is:
 
 "System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.ObjectModel.KeyedCollection`2.AddKey(TKey key, TItem item)
   at System.Collections.ObjectModel.KeyedCollection`2.InsertItem(Int32 index, TItem item)
   at Granfeldt.PowerShellManagementAgent.Microsoft.MetadirectoryServices.IMAExtensible2CallExport.PutExportEntries(IList`1 csentries)
Forefront Identity Manager 4.4.1642.0"
```

The changes were made in the connected subsystem.

**Comment by sorengranfeldt** [comment]
So not a problem in the PSMA then ? Right?

**Comment by christianbormann** [comment]
Yes, a problem in my export.ps1 code. Sorry for opening an issue.
