### ISSUE TITLE
cannot refresh extension on create agent

### ISSUE THREAD

**Issue by bzuidgeest** [sorengranfeldt/psma#16]
I tried creating an agent after installation, but it gives me an error that the extension cannot be refreshed.

I found the following in the event viewer:

The server encountered an unexpected error:
 
 "Could not load file or assembly 'file:///C:\Program Files\Microsoft Forefront Identity Manager\2016\Synchronization Service\Extensions\Granfeldt.PowerShell.ManagementAgent.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)

   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Microsoft.MetadirectoryServices.Impl.ScriptHost.InitializeWorker(InitializeArguments pArgs)

InnerException=>
An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See  for more information.

Latest version of mim with SP and rollups. On a windows server 2019.

Is the cause known?

**Comment by bzuidgeest** [comment]
O never mind, I restarted the sync service itself and it started working.
